### ISSUE TITLE
update_config: command not found

### ISSUE THREAD

**Issue by brase** [tiredofit/docker-self-service-password#33]
Something seems to be strange in the latest version?

I am getting a lot of these when starting the image:

```
  password    | + update_config ldap_url ldap
  password    | /var/run/s6/etc/cont-init.d/30-self-service-password: line 26: update_config: command not found
```

This are my ENV-Variables:

```
  DEBUG_MODE: "true"
  SETUP_TYPE: "AUTO"

  ...
  LDAP_* Settings
  ...
  PASSWORD_HASH: "SSHA"

  SAMBA_MODE: "true"
  USE_TOKENS: "false"
  TOKEN_CRYPT: "false"
```

Does anybody has an idea whats going wrong here? Thank you!

**Comment by tiredofit** [comment]
Please check to make sure you are on the latest version by doing a `docker pull tiredofit/self-service-password:latest` And if you can send me the full logs from startup that would be wonderfu. Please redact anything confidential. You can send to my email which is listed in the changelog (dave).

**Comment by brase** [comment]
Okay, using "latest" fixed it.

Normaly I use the last tagged version to get reproducable builds but 5.1.1 seems to be broken.

**Comment by tiredofit** [comment]
To that I apologize. Docker Hub went on the fritz a couple weeks ago and walked all over the build process. Due to the way the images are setup as bases, it went ahead and built the tagged version first, instead of letting the bases build beforehand. I will remove 5.1.1 entirely from Docker Hub to avoid confusion.
